services:
  opensw-prod:
    build:
      context: .
      dockerfile: Dockerfile.prod
    image: opensw:latest
    container_name: opensw
    expose:
      - 80
    ports:
      - 13080:80
    environment:
      TZ: Asia/Seoul
    restart: unless-stopped
    networks:
      net:
        ipv4_address: 172.22.22.108

networks:
  net:
    external: true