services:
  opensw-dev:
    build:
      context: .
      dockerfile: Dockerfile
    image: opensw-dev:latest
    container_name: prj-opensw-dev
    expose:
      - 3000
#    ports:
#      - 13000:3000
    environment:
      TZ: Asia/Seoul
    restart: unless-stopped
    develop:
      watch:
        - action: sync
          path: src
          target: src
          ignore:
            - .vscode
        - action: sync
          path: public
          target: public
        - action: sync
          path: index.html
          target: index.html
        - action: sync+restart
          path: .env.development
          target: .env.development
        - action: sync+restart
          path: vite.config.js
          target: vite.config.js
        - action: rebuild
          path: package*.json
    networks:
      net:
        ipv4_address: 172.22.22.107

networks:
  net:
    external: true